config/routes.rb
Rails.application.routes.draw do

  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_scope :customer do
    post "customers/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  scope module: :public do
    root to: "homes#top"
    get "/about" => "homes#about"
    resources :notifications, only: :index
    resources :posts, only:[:index, :show, :edit, :destroy, :create, :update] do
      resources :bookmarks, only: [:index, :create, :destroy]
      resources :comments, only: [:create]
    end
    resources :comments, only: [:destroy]
    delete "/notifications/destroy_all" => "notifications#destroy_all", as: "destroy_all_notifications"
    get "/customers/unsubscribe" => "customers#unsubscribe"
    patch "/customers/withdraw" => "customers#withdraw"
    resources :customers, only: [:index, :show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
      get "followers" => "relationships#followers", as: "followers"
    end
    get "search" => "searches#search"
  end

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    patch "/customers/withdraw" => "customers#withdraw"
    resources :customers, only: [:index, :show, :edit, :update]
    resources :posts, only:[:index, :show, :destroy]
    get "search" => "searches#search"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_many :active_notifications, class_name: "Notification", foreign_key: "visiter_id", dependent: :destroy
  has_many :passive_notifications, class_name: "Notification", foreign_key: "visited_id", dependent: :destroy

  def create_notification_follow!(current_customer)
    temp = Notification.where(["visiter_id = ? and visited_id = ? and action = ? ",current_customer.id, id, 'follow'])
    if temp.blank?
      notification = current_customer.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end

  def self.guest
    find_or_create_by!(name: 'ゲスト' ,email: 'guest@example.com') do |customer|
      customer.password = SecureRandom.urlsafe_base64
      customer.name = "ゲスト"
    end
  end

  def follow(customer_id)
    relationships.create(followed_id: customer_id)
  end
  def unfollow(customer_id)
    relationships.find_by(followed_id: customer_id).destroy
  end
  def following?(customer)
    followings.include?(customer)
  end

  validates :name, length: { maximum: 20 }, uniqueness: true
  validates :introduction, length: {maximum: 50}

  def self.looks(search, word)
   if search == "perfect_match"
     @customer = Customer.where("name LIKE?","#{word}")
   elsif search == "forward_match"
     @customer = Customer.where("name LIKE?","#{word}%")
   elsif search == "backward_match"
     @customer = Customer.where("name LIKE?","%#{word}")
   elsif search == "partial_match"
     @customer = Customer.where("name LIKE?","%#{word}%")
   else
     @customer = Customer.all
   end
  end

  def active_for_authentication?
    super && (is_deleted == false)
  end

  def get_profile_image
    (profile_image.attached?) ? profile_image : 'busyou.png'
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
before_action :authenticate_admin!

  def show
    @customer = Customer.find(params[:id])
    @posts = @customer.posts.page(params[:page]).per(5)
  end

  def index
    @customers = Customer.page(params[:page]).per(10)
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      flash[:notice] = "編集しました"
      redirect_to admin_customer_path(@customer)
    else
      render :edit
    end
  end

  def customer_params
    params.require(:customer).permit(:name, :introduction, :profile_image, :is_deleted)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/_info.html.erb
<div class="profile_image text-center"><%= image_tag customer.get_profile_image, size:"200x200" %></div>
<table class="table mt-4 table" style="table-layout:fixed;width:100%;">
  <tr>
	  <th class="col-xs-2">会員名<br><%= customer.name %></th>
  </tr>
  <tr>
	  <th class="col-xs-3" style="word-wrap: break-word; width: 200px;">自己紹介<br><%= customer.introduction %></th>
  </tr>
  <tr>
    <th class="status col-xs-4">ステータス:</th>
    <% if @customer.is_deleted == false %>
      <th class="text-success font-weight-bold">有効</th>
    <% else %>
      <th class="text-muted font-weight-bold">退会</th>
    <% end %>
  </tr>
  <tr>
    <th><%= link_to "編集する", edit_admin_customer_path(@customer.id), class: "btn btn-success" %></th>
  </tr>
</table>

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>会員情報編集</h2>
    <%= form_with model:@customer, url: admin_customer_path, local:true do |f| %>
      <div class="form-group">
        <%= f.label :"プロフィール画像" %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: "image/*" %>
      </div>
      <div class="form-group">
        <%= f.label :"会員名" %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
      <div class="form-group">
        <%= f.label :"自己紹介" %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.label :"会員ステータス", class: "control-label" %><br>
        <%= f.radio_button :is_deleted, false, checked: true %><%= f.label :is_deleted, "有効" %>
        <%= f.radio_button :is_deleted, true %><%= f.label :is_deleted, "退会" %>
      </div>
      <div class="form-group">
        <%= f.submit "変更を保存", class: "btn btn-secondary rounded-pill" %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row" style="margin-top:25px;">
    <div class="col-sm-8 px-sm-0 offset-sm-1">
      <h4>会員一覧</h4>
    </div>
    <div class="col-sm-10 px-sm-0 mx-auto mb-5">
    <table class="table table-hover">
      <thead class="table-active">
        <tr>
          <th>会員ID</th>
          <th>名前</th>
          <th>メールアドレス</th>
          <th>会員ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @customers.each do |customer| %>
        <tr>
          <td><%= customer.id %></td>
          <td><%= link_to customer.name, admin_customer_path(customer), class: "text-dark font-weight-bold" %></td>
          <td><%= customer.email %></td>
          <% if customer.is_deleted == false %>
            <td class="text-success font-weight-bold">有効</td>
          <% else %>
            <td class="text-muted">退会</td>
          <% end %>
        </tr>
        <% end %>
      </tbody>
    </table>
    <div class="mx-auto font-weight-bold" style="width:200px;">
      <%= paginate @customers %>
    </div>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2><%= @customer.name %>さんの会員詳細</h2>
      <%= render 'info', customer: @customer %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>投稿</h2>
      <%= render 'admin/posts/index',posts: @posts %>
      <%= paginate @posts %>
    </div>
  </div>
</div>

app/views/admin/customers/unsubscribe.html.erb
<div class="container">
  <div class="row">
    <div class="col text-center m-5">
      <h2><strong>本当に退会しますか？</strong></h2>

    <div class="unsubscribe-msg mt-5">
      <strong>
      退会すると会員情報登録や<br>
      これまでの購入履歴が閲覧できなくなります。<br>
      退会する場合は,「退会する」をクリックしてください。
      </strong>
    </div>
    <div class="bottom mt-4">
      <%= link_to "退会しない", customers_path, class: 'glyphicon glyphicon-home btn-lg btn-primary' %>
      <%= link_to "退会する", customers_withdraw_path, method: :patch, data: {confirm: "本当に退会してもよろしいですか？"}, class: "glyphicon glyphicon-tint btn-lg btn-danger ml-5" %>
    </div>
    </div>
  </div>
</div>