config/routes.rb
Rails.application.routes.draw do

  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_scope :customer do
    post "customers/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  scope module: :public do
    root to: "homes#top"
    get "/about" => "homes#about"
    resources :notifications, only: :index
    resources :posts, only:[:index, :show, :edit, :destroy, :create, :update] do
      resources :bookmarks, only: [:index, :create, :destroy]
      resources :comments, only: [:create]
    end
    resources :comments, only: [:destroy]
    delete "/notifications/destroy_all" => "notifications#destroy_all", as: "destroy_all_notifications"
    get "/customers/unsubscribe" => "customers#unsubscribe"
    patch "/customers/withdraw" => "customers#withdraw"
    resources :customers, only: [:index, :show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
      get "followers" => "relationships#followers", as: "followers"
    end
    get "search" => "searches#search"
  end

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    patch "/customers/withdraw" => "customers#withdraw"
    resources :customers, only: [:index, :show, :edit, :update]
    resources :posts, only:[:index, :show, :destroy]
    get "search" => "searches#search"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/searches_controller.rb
class Admin::SearchesController < ApplicationController
before_action :authenticate_admin!

  def search
    @text = params[:word]
    @range = params[:range]
    if @range == "会員名"
      @customers = Customer.looks(params[:search], params[:word]).page(params[:page]).per(5)
    else
      @posts = Post.looks(params[:search], params[:word]).page(params[:page]).per(5)
    end
  end
end

app/helpers/admin/searchs_helper.rb
module Admin::SearchsHelper
end

app/views/admin/searches/_search.html.erb
<div class="search_form">
  <%= form_with url: admin_search_path, local: true, method: :get do |f| %>
    <%= f.text_field :word %>
    <%= f.select :range, options_for_select([["会員名"], ["城名"]]) %>
    <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backward_match"], ["部分一致","partial_match"]]) %>
    <%= f.submit "検索", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/admin/searches/search.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-8 offset-md-1">
      <% if @range == "会員名" %>
        <h2>"<%= @text %>"の検索結果</h2>
        <div class="container px-5 px-sm-0">
          <div class="row" style="margin-top:25px;">
            <div class="col-sm-8 px-sm-0 offset-sm-1">
              <h4>会員一覧</h4>
            </div>
            <div class="col-sm-10 px-sm-0 mx-auto mb-5">
            <table class="table table-hover">
              <thead class="table-active">
                <tr>
                  <th>会員ID</th>
                  <th>名前</th>
                  <th>メールアドレス</th>
                  <th colspan="3"></th>
                </tr>
              </thead>
              <tbody>
                <% @customers.each do |customer| %>
                <tr>
                  <td><%= customer.id %></td>
                  <td><%= link_to customer.name, admin_customer_path(customer), class: "text-dark font-weight-bold" %></td>
                  <td><%= customer.email %></td>
                </tr>
                <% end %>
              </tbody>
            </table>
            </div>
          </div>
        </div>
      <% else %>
        <h2>"<%= @text %>"の検索結果</h2>
        <table class="table">
          <thead>
            <tr>
              <th></th>
              <th>城名</th>
              <th>感想</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @posts.each do |post| %>
              <tr>
                <td class="text-center">
                  <%= link_to admin_post_path(post.id) do %>
                    <%= image_tag post.image, size: "100x100" %>
                  <% end %>
                </td>
                <td class="pt-5"><%= post.customer.name %></td>
                </td>
                <td class="pt-5"><%= post.castle %></td>
                <td class="pt-5 text-truncate" style="max-width: 150px;">
                  <%= post.body %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% end %>
    </div>
  </div>
</div>
<div style="position: fixed; bottom: 100px; margin-left: 375px;">
  <% if @range == "会員名" %>
    <%= paginate @customers %>
  <% else %>
    <%= paginate @posts %>
  <% end %>
</div>