config/routes.rb
Rails.application.routes.draw do

  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_scope :customer do
    post "customers/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  scope module: :public do
    root to: "homes#top"
    get "/about" => "homes#about"
    resources :notifications, only: :index
    resources :posts, only:[:index, :show, :edit, :destroy, :create, :update] do
      resources :bookmarks, only: [:index, :create, :destroy]
      resources :comments, only: [:create]
    end
    resources :comments, only: [:destroy]
    delete "/notifications/destroy_all" => "notifications#destroy_all", as: "destroy_all_notifications"
    get "/customers/unsubscribe" => "customers#unsubscribe"
    patch "/customers/withdraw" => "customers#withdraw"
    resources :customers, only: [:index, :show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
      get "followers" => "relationships#followers", as: "followers"
    end
    get "search" => "searches#search"
  end

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    patch "/customers/withdraw" => "customers#withdraw"
    resources :customers, only: [:index, :show, :edit, :update]
    resources :posts, only:[:index, :show, :destroy]
    get "search" => "searches#search"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<header class="bg-secondary text-monospace">
  <nav class="navbar navbar-expand-lg navbar-dark p-0">
    <div class="container ">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="nav navbar-nav ml-auto">
          <% if admin_signed_in? %>
            <li>
              <%= link_to "投稿一覧", admin_posts_path, class: "nav-link text-light" %>
            </li>
            <li >
              <%= link_to "会員一覧", admin_customers_path, class: "nav-link text-light" %>
            </li>
            <li>
              <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "nav-link text-light" %>
            </li>
            <li class="nav-link">
              <%= render "admin/searches/search" %>
            </li>
          <% elsif customer_signed_in? %>
            <li>
              <%= link_to "マイページ", customer_path(current_customer), class: "nav-link text-light" %>
            </li>
            <li>
              <%= link_to "会員一覧", customers_path, class: "nav-link text-light" %>
            </li>
            <li>
              <%= link_to "投稿/投稿一覧", posts_path, class: "nav-link text-light" %>
            </li>
            <li class="notification"><%= link_to "通知", notifications_path, class: "nav-link text-light" %></li>
            <% if unchecked_notifications.any? %>
              <i class="fa fa-circle notification-circle pr-2"></i>
            <% end %>
            <li>
              <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "nav-link text-light" %>
            </li>
            <li class="nav-link">
              <%= render "public/searches/search" %>
            </li>
          <% else %>
            <div class="nav collapse navbar-collapse" id="navbarNavDropdown">
              <ul class="navbar-nav ml-auto">
                <li>
                  <%= link_to "ホーム", root_path, class: "nav-link text-light" %>
                </li>
                <li>
                  <%= link_to "新規登録", new_customer_registration_path, data: {"turbolinks" => false}, class: "nav-link text-light" %>
                </li>
                <li>
                  <%= link_to "ログイン", new_customer_session_path, class: "nav-link text-light" %>
                </li>
              </ul>
            </div>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shirozeme</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://fonts.googleapis.com/earlyaccess/hannari.css" rel="stylesheet">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= stylesheet_pack_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <% unless current_page?(root_path) %>
      <%= render "layouts/header" %>
    <% end %>
    <main>
      <p class="notice" id="notice"><%= notice %></p>
      <%= yield %>
    </main>
  </body>
</html>